name: Unzip Textures
on: workflow_dispatch
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip data.zip -d data/
          rm data.zip
          git config user.name "Automated Bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "Successfully extracted all 80 asset folders"
          git push
